export const MOVIE_DETAILS_KEY = [
  "Director",
  "Writer",
  "Actors",
  "Language",
  "Awards",
  "imdbRating",
  "imdbVotes",
  "BoxOffice",
];
export const movieReviewData = {
  Title: "The Incredible Hulk",
  Year: "2008",
  Rated: "PG-13",
  Released: "13 Jun 2008",
  Runtime: "112 min",
  Genre: "Action, Adventure, Sci-Fi",
  Director: "Louis Leterrier",
  Writer: "Zak Penn, Stan Lee, Jack Kirby",
  Actors: "Edward Norton, Liv Tyler, Tim Roth",
  Plot: "Bruce Banner, a scientist on the run from the U.S. Government, must find a cure for the monster he turns into whenever he loses his temper.",
  Language: "English, Portuguese, Spanish",
  Country: "United States, Canada",
  Awards: "2 wins & 10 nominations",
  Poster:
    "https://m.media-amazon.com/images/M/MV5BMTUyNzk3MjA1OF5BMl5BanBnXkFtZTcwMTE1Njg2MQ@@._V1_SX300.jpg",
  Ratings: [
    {
      Source: "Internet Movie Database",
      Value: "6.6/10",
    },
    {
      Source: "Rotten Tomatoes",
      Value: "67%",
    },
    {
      Source: "Metacritic",
      Value: "61/100",
    },
  ],
  Metascore: "61",
  imdbRating: "6.6",
  imdbVotes: "519,538",
  imdbID: "tt0800080",
  Type: "movie",
  DVD: "12 Feb 2014",
  BoxOffice: "$134,806,913",
  Production: "N/A",
  Website: "N/A",
  Response: "True",
};
